### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by JHouterman** [thomasverkooijen/Catstacking#11]
Will differentiate the stages of a level
Pans the camera up in a smooth motion
provides the stage (size will be variable) with a floor on which the player can continue building their tower

**Comment by thomasverkooijen** [comment]
Rewrite should include fixes for issues 12, 14 and 21. Floor should get a proper sprite (using ugly stretched one for now, is unreadable). Fluid motion will be achieved once tweening is applied, investigating options.

**Comment by JHouterman** [comment]
Hold off on signoff until bug-free
