### ISSUE TITLE
New Pass Temple of Our Fathers

### ISSUE THREAD

**Issue by Stoic** [thomasverkooijen/Catstacking#92]

**Comment by Stoic** [comment]
https://drive.google.com/open?id=0BzHmx1kPvHnzaWZQVzVsOWJxS2s&authuser=0

**Comment by Stoic** [comment]
https://www.youtube.com/watch?v=oSiuLeBOGlM

**Comment by JHouterman** [comment]
I take it the bloodborne link was an accident?

Waterline still looks too much like a photo, please make it more painted.
